spring.application.name=AuthSecurity
spring.security.user.name=shravan
spring.security.user.password=shravan
#Database url
spring.datasource.url=jdbc:mysql://localhost:3306/auth_security
#Database credentials
spring.datasource.username=root
spring.datasource.password=shravan
#JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect